# Generated by Django 3.0.8 on 2020-08-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_extendeduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Customer'),
        ),
    ]
