# Generated by Django 3.0.8 on 2020-08-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200828_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receive',
            field=models.BooleanField(default=False),
        ),
    ]
