# Generated by Django 3.0.8 on 2020-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_order_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
