# Generated by Django 3.0.8 on 2020-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20200829_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(default=60, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date1',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
