# Generated by Django 3.0.8 on 2020-09-09 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_date1']},
        ),
    ]
