# Generated by Django 3.0.8 on 2020-09-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200909_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date_created']},
        ),
    ]
