# Generated by Django 3.0.8 on 2020-09-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20200914_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
