# Generated by Django 3.0.8 on 2020-09-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20200914_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
