# Generated by Django 3.0.8 on 2020-09-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_remove_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
