# Generated by Django 3.0.8 on 2020-09-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_auto_20200917_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
